apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vso

dependsOn:
  - name: vso-crds

resources:
  - operator.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - token-secret.yaml