apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vso

resources:
  - namespace.yaml
  - helmrepo.yaml
  - crds.yaml
  - operator.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - token-secret.yaml
  - vaultconnection.yaml
  - vaultauth.yaml