apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnativepg.yaml
  - eck.yaml
  - otel.yaml
configMapGenerator:
- name: otel-values
  namespace: observability
  files:
    - values.yaml=values.yaml