apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vso-namespace
  - ./vso-crds
  - ./vso-operator
  - ./vso-auth
  #- cnpg.yaml
  #- eck.yaml
  #- otel.yaml
  #- minio.yaml
  - mariadb.yaml
  #- strimzi.yaml
#configMapGenerator:
#  - name: otel-values
#    namespace: opentelemetry-operator-system  
#    files:
#      - values.yaml
#generatorOptions:
#  disableNameSuffixHash: true