apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg.yaml
  - eck.yaml
  - otel.yaml
  #- vault.yaml
  #- minio.yaml
  #- strimzi.yaml
configMapGenerator:
  - name: otel-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true