apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-sa.yaml
  - vaultauth-static.yaml
  - vaultstaticsecret-mariadb-admin.yaml
  - mariadb.yaml
  - user-admin.yaml
  - database-wordpress.yaml